pre-commit.ci:
  autofix_commit_msg: |
    chore [pre-commit.ci] commit: auto fixes from pre-commit.ci hooks
  autoupdate_commit_msg: |
    chore [pre-commit.ci] pre-commit autoupdate
  autofix_prs: true
  autoupdate_branch: epic-kore
  autoupdate_schedule: monthly
  push:
    branches:
      - epic-kore
  skip:
    - editorconfig-checker
    - trailing-whitespace
    - end-of-file-fixer
    - mixed-line-ending
    - check-yaml
  submodules: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^staticfiles/admin/|^docs/
      - id: check-yaml
        exclude: ^pep8speaks\.yml$
      - id: end-of-file-fixer
        exclude: ^staticfiles/|^docs/
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        args:
          - --check
#  - repo: https://github.com/Yelp/detect-secrets
#    rev: v1.0.3
#    hooks:
#      - id: detect-secrets
#        args: ['--baseline', 'secrets.baseline']
#        exclude: 'secrets.baseline'
#  - repo: https://github.com/PyCQA/bandit
#    rev: 1.7.5
#    hooks:
#      - id: bandit
#        args: ["-r", "-lll"]
#        exclude: *fixtures
