"""
Django Base Settings for dash_and_do project.

Generated by 'django-admin startproject' using Django 4.2.3. (LTS)

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/

Changelog:
2023-08-09
- Added `sys` for appending apps to base directory.
- Added apps to `INSTALLED_APPS` for v0.5, v1.0
- Added `django_environ` for .env file support.
- Updated BASE_DIR to search: 2 to 3 parents: for Setting folder
- Updated: Template Base Directory + project templates to search.
- Updated: Canonical values added from.env as per 12 Factor.Config
"""

#  Copyright (c) 2023.

import os
import sys

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# ================== Django Application Grouping ==================
# Project Structure: Top Level Refactoring / Applications Grouping
# Adds additional new sources root directory.
# Benefits to this:
# a) reference to apps by name in INSTALLED_APPS.
# b) Grouping apps in own directory.

sys.path.append(str(BASE_DIR / 'apps'))

# ================== Environment Variables ==================
# Read the .env file
# Assign the values from the .env variables

env = Env()
env_file = os.path.join(BASE_DIR, '.env')

# Be defensive, check if the file exists by default.
if not os.path.isfile(env_file):
    raise FileNotFoundError(f"{env_file} not found")

env.read_env(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

WSGI_APPLICATION = env.str('WSGI_APPLICATION')

ALLOWED_HOSTS = []

ROOT_URLCONF = env.str('ROOT_URLCONF')

# Application definition
# Updated: Added apps to `INSTALLED_APPS`

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Customization with env variables for canonical values.
    env.str('CORE_APP'),
    env.str('USERS_APP'),
    env.str('DASH_APP'),
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Updated : 2023-08-09
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Development Database moved to development.py
# Production Database moved to production.py

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.\
                password_validation'
                '.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.\
                 auth.password_validation'
                '.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.\
                 auth.password_validation'
                '.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.\
                 auth.password_validation'
                '.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = env.str('LOCALE')

TIME_ZONE = env.str('TIME_ZONE')

USE_I18N = env.bool('USE_I18N')

USE_TZ = env.bool('USE_TZ')

# ==================== File & Uploads ====================

# Media Files (Uploads), Untrustowrthy

MEDIA_URL = env.str('MEDIA_URL', default='media/')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = env.str('STATIC_URL', default='static/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from .thirdparty import *  # noqa
